#!/usr/bin/env bash

set -e

# install ssh key/pair and authorized_keys on node
if [[ -f $VAGRANT_DIR/etc/ssh/id_rsa ]]; then
  mkdir -p ~/.ssh
  
  mv $VAGRANT_DIR/etc/ssh/id_rsa ~/.ssh/
  mv $VAGRANT_DIR/etc/ssh/id_rsa.pub ~/.ssh/
  
  chmod 700 ~/.ssh
  chmod 600 ~/.ssh/id_rsa ~/.ssh/id_rsa.pub
fi
